In [190]:
import pandas as pd
import numpy as np
import xlsxwriter as xw

info = pd.read_excel("D:\jupyter notebook 保存文件\提取的运动学片段\运动学片段三次改进C001296554216.xlsx")
data1 = pd.DataFrame(info)
result = data1.values

excel = pd.read_excel("D:\jupyter notebook 保存文件\已经预处理的文件\预处理C001296554216.xlsx")
data2 = pd.DataFrame(excel)
data_a = data2.values  # 变为数组

print("开始计算特征值")
feature = []
#计算特征值
for i in range(len(result)):

    m = result[i][0]  # 运动学片段开始点
    n = result[i][1]  # 运动学片段怠速状态结束点
    k = result[i][2]+1  # 运动学片段结束点
    v_average = sum(data_a[m:k,9])/(k-m)#平均速度
    v_average_travel = sum(data_a[n:k,9])/(k-n)#平均行驶速度
    v_max = max(data_a[m:k,9])#最大速度
    #加减速
    plus = []#加速
    slow = []#减速
    uniformity = []#匀速
    for j in range(n+1,k):
        acc = data_a[j][10]#索引10为加速度
        v = data_a[j][9]
        if acc > 0.1:
            plus.append(acc)
        if acc < -0.1:
            slow.append(acc)
        if acc <= 0.1 and acc >= -0.1 and v !=0 :
            uniformity.append(acc)
    # 平均加速度
    if len(plus)==0:
        plus_average =0
    else:
        plus_average = sum(plus)/len(plus)
    # 平均减速度
    if len(slow)==0:
        slow_average =0
    else:
        slow_average = sum(slow)/len(slow)
    #slow_average = sum(slow)/len(slow)
    # 速度标准差
    v_std = np.std(data_a[m:k,9])
    # 加速度标准差
    plus_std = np.std(plus)
    # 减速度标准差
    slow_std = np.std(slow)
    # 运动学片段时长
    time = k - m
    # 怠速时间
    time_0 = n - m+1
    # 加速时间
    time_1 = len(plus)
    # 减速时间
    time_2 = len(slow)
    # 匀速时间
    time_3 = len(uniformity)
    # 怠速时间比
    ratio_0 = time_0/time
    # 加速时间比
    ratio_1 = time_1 / time
    # 减速时间比
    ratio_2 = time_2 / time
    # 匀速时间比
    ratio_3 = time_3 / time
   
    
    all = [v_average,v_average_travel,v_max,plus_average,slow_average,v_std,plus_std,slow_std,time,time_0,time_1,time_2,time_3,ratio_0,ratio_1,ratio_2,ratio_3]
    feature.append(all)

print("开始写入表格")
from pandas.core.frame import DataFrame
data=DataFrame(feature)
data.columns=["平均速度","平均行驶速度","最大速度","平均加速度","平均减速度","速度标准差","加速度标准差","减速度标准差","运动学片段时间长度","怠速时间","加速时间","减速时间","匀速时间","怠速时间比","加速时间比","减速时间比","匀速时间比"]  # 设置表头

data.to_excel('特征值二次改进C001296554216.xlsx',index=None)                          
data

开始计算特征值
开始写入表格

,平均速度,平均行驶速度,最大速度,平均加速度,平均减速度,速度标准差,加速度标准差,减速度标准差,运动学片段时间长度,怠速时间,加速时间,减速时间,匀速时间,怠速时间比,加速时间比,减速时间比,匀速时间比
0,0.138889,0.185185,0.555556,0.111111,-0.111111,0.182151,0.000000,0.000000,20,6,1,1,8,0.300000,0.050000,0.050000,0.400000
1,0.163194,0.326389,0.833333,0.156250,-0.177778,0.247942,0.042526,0.064788,40,21,3,5,7,0.525000,0.075000,0.125000,0.175000
2,0.185185,0.185185,0.555556,0.111111,-0.111111,0.188853,0.000000,0.000000,15,1,1,1,8,0.066667,0.066667,0.066667,0.533333

In [191]:
import pandas as pd
import numpy as np
import xlsxwriter as xw

info = pd.read_excel("D:\jupyter notebook 保存文件\提取的运动学片段\运动学片段三次改进C001474927705.xlsx")
data1 = pd.DataFrame(info)
result = data1.values

excel = pd.read_excel("D:\jupyter notebook 保存文件\已经预处理的文件\预处理C001474927705.xlsx")
data2 = pd.DataFrame(excel)
data_a = data2.values  # 变为数组

print("开始计算特征值")
feature = []
#计算特征值
for i in range(len(result)):

    m = result[i][0]  # 运动学片段开始点
    n = result[i][1]  # 运动学片段怠速状态结束点
    k = result[i][2]+1  # 运动学片段结束点
    v_average = sum(data_a[m:k,9])/(k-m)#平均速度
    v_average_travel = sum(data_a[n:k,9])/(k-n)#平均行驶速度
    v_max = max(data_a[m:k,9])#最大速度
    #加减速
    plus = []#加速
    slow = []#减速
    uniformity = []#匀速
    for j in range(n+1,k):
        acc = data_a[j][10]#索引10为加速度
        v = data_a[j][9]
        if acc > 0.1:
            plus.append(acc)
        if acc < -0.1:
            slow.append(acc)
        if acc <= 0.1 and acc >= -0.1 and v !=0 :
            uniformity.append(acc)
    # 平均加速度
    if len(plus)==0:
        plus_average =0
    else:
        plus_average = sum(plus)/len(plus)
    # 平均减速度
    if len(slow)==0:
        slow_average =0
    else:
        slow_average = sum(slow)/len(slow)
    #slow_average = sum(slow)/len(slow)
    # 速度标准差
    v_std = np.std(data_a[m:k,9])
    # 加速度标准差
    plus_std = np.std(plus)
    # 减速度标准差
    slow_std = np.std(slow)
    # 运动学片段时长
    time = k - m
    # 怠速时间
    time_0 = n - m+1
    # 加速时间
    time_1 = len(plus)
    # 减速时间
    time_2 = len(slow)
    # 匀速时间
    time_3 = len(uniformity)
    # 怠速时间比
    ratio_0 = time_0/time
    # 加速时间比
    ratio_1 = time_1 / time
    # 减速时间比
    ratio_2 = time_2 / time
    # 匀速时间比
    ratio_3 = time_3 / time
   
    
    all = [v_average,v_average_travel,v_max,plus_average,slow_average,v_std,plus_std,slow_std,time,time_0,time_1,time_2,time_3,ratio_0,ratio_1,ratio_2,ratio_3]
    feature.append(all)

print("开始写入表格")
from pandas.core.frame import DataFrame
data=DataFrame(feature)
data.columns=["平均速度","平均行驶速度","最大速度","平均加速度","平均减速度","速度标准差","加速度标准差","减速度标准差","运动学片段时间长度","怠速时间","加速时间","减速时间","匀速时间","怠速时间比","加速时间比","减速时间比","匀速时间比"]  # 设置表头

data.to_excel('特征值二次改进C001474927705.xlsx',index=None)                          
data

开始计算特征值
开始写入表格

,平均速度,平均行驶速度,最大速度,平均加速度,平均减速度,速度标准差,加速度标准差,减速度标准差,运动学片段时间长度,怠速时间,加速时间,减速时间,匀速时间,怠速时间比,加速时间比,减速时间比,匀速时间比
0,0.517361,0.591270,1.111111,0.117670,-0.144444,0.390002,0.012836,0.015713,40,6,4,3,24,0.150000,0.100000,0.075,0.600000
1,0.134259,0.268519,0.833333,0.231481,-0.125000,0.238100,0.046296,0.009488,30,16,2,6,2,0.533333,0.066667,0.200,0.066667

In [192]:
import pandas as pd
import numpy as np
import xlsxwriter as xw

info = pd.read_excel("D:\jupyter notebook 保存文件\提取的运动学片段\运动学片段三次改进C001291925081.xlsx")
data1 = pd.DataFrame(info)
result = data1.values

excel = pd.read_excel("D:\jupyter notebook 保存文件\已经预处理的文件\预处理C001291925081.xlsx")
data2 = pd.DataFrame(excel)
data_a = data2.values  # 变为数组

print("开始计算特征值")
feature = []
#计算特征值
for i in range(len(result)):

    m = result[i][0]  # 运动学片段开始点
    n = result[i][1]  # 运动学片段怠速状态结束点
    k = result[i][2]+1  # 运动学片段结束点
    v_average = sum(data_a[m:k,9])/(k-m)#平均速度
    v_average_travel = sum(data_a[n:k,9])/(k-n)#平均行驶速度
    v_max = max(data_a[m:k,9])#最大速度
    #加减速
    plus = []#加速
    slow = []#减速
    uniformity = []#匀速
    for j in range(n+1,k):
        acc = data_a[j][10]#索引10为加速度
        v = data_a[j][9]
        if acc > 0.1:
            plus.append(acc)
        if acc < -0.1:
            slow.append(acc)
        if acc <= 0.1 and acc >= -0.1 and v !=0 :
            uniformity.append(acc)
    # 平均加速度
    if len(plus)==0:
        plus_average =0
    else:
        plus_average = sum(plus)/len(plus)
    # 平均减速度
    if len(slow)==0:
        slow_average =0
    else:
        slow_average = sum(slow)/len(slow)
    #slow_average = sum(slow)/len(slow)
    # 速度标准差
    v_std = np.std(data_a[m:k,9])
    # 加速度标准差
    plus_std = np.std(plus)
    # 减速度标准差
    slow_std = np.std(slow)
    # 运动学片段时长
    time = k - m
    # 怠速时间
    time_0 = n - m+1
    # 加速时间
    time_1 = len(plus)
    # 减速时间
    time_2 = len(slow)
    # 匀速时间
    time_3 = len(uniformity)
    # 怠速时间比
    ratio_0 = time_0/time
    # 加速时间比
    ratio_1 = time_1 / time
    # 减速时间比
    ratio_2 = time_2 / time
    # 匀速时间比
    ratio_3 = time_3 / time
   
    
    all = [v_average,v_average_travel,v_max,plus_average,slow_average,v_std,plus_std,slow_std,time,time_0,time_1,time_2,time_3,ratio_0,ratio_1,ratio_2,ratio_3]
    feature.append(all)

print("开始写入表格")
from pandas.core.frame import DataFrame
data=DataFrame(feature)
data.columns=["平均速度","平均行驶速度","最大速度","平均加速度","平均减速度","速度标准差","加速度标准差","减速度标准差","运动学片段时间长度","怠速时间","加速时间","减速时间","匀速时间","怠速时间比","加速时间比","减速时间比","匀速时间比"]  # 设置表头

data.to_excel('特征值二次改进C001291925081.xlsx',index=None)                          
data

开始计算特征值
开始写入表格

,平均速度,平均行驶速度,最大速度,平均加速度,平均减速度,速度标准差,加速度标准差,减速度标准差,运动学片段时间长度,怠速时间,加速时间,减速时间,匀速时间,怠速时间比,加速时间比,减速时间比,匀速时间比
0,0.541667,0.541667,1.111111,0.191485,-0.137307,0.302830,0.076449,0.034937,80,1,17,18,42,0.0125,0.212500,0.225000,0.525000
1,0.185185,0.222222,0.555556,0.111111,-0.111111,0.188853,0.000000,0.000000,30,6,2,2,16,0.2000,0.066667,0.066667,0.533333

In [193]:
import pandas as pd
import numpy as np
import xlsxwriter as xw

info = pd.read_excel("D:\jupyter notebook 保存文件\提取的运动学片段\运动学片段三次改进C001803284019.xlsx")
data1 = pd.DataFrame(info)
result = data1.values

excel = pd.read_excel("D:\jupyter notebook 保存文件\已经预处理的文件\预处理C001803284019.xlsx")
data2 = pd.DataFrame(excel)
data_a = data2.values  # 变为数组

print("开始计算特征值")
feature = []
#计算特征值
for i in range(len(result)):

    m = result[i][0]  # 运动学片段开始点
    n = result[i][1]  # 运动学片段怠速状态结束点
    k = result[i][2]+1  # 运动学片段结束点
    v_average = sum(data_a[m:k,9])/(k-m)#平均速度
    v_average_travel = sum(data_a[n:k,9])/(k-n)#平均行驶速度
    v_max = max(data_a[m:k,9])#最大速度
    #加减速
    plus = []#加速
    slow = []#减速
    uniformity = []#匀速
    for j in range(n+1,k):
        acc = data_a[j][10]#索引10为加速度
        v = data_a[j][9]
        if acc > 0.1:
            plus.append(acc)
        if acc < -0.1:
            slow.append(acc)
        if acc <= 0.1 and acc >= -0.1 and v !=0 :
            uniformity.append(acc)
    # 平均加速度
    if len(plus)==0:
        plus_average =0
    else:
        plus_average = sum(plus)/len(plus)
    # 平均减速度
    if len(slow)==0:
        slow_average =0
    else:
        slow_average = sum(slow)/len(slow)
    #slow_average = sum(slow)/len(slow)
    # 速度标准差
    v_std = np.std(data_a[m:k,9])
    # 加速度标准差
    plus_std = np.std(plus)
    # 减速度标准差
    slow_std = np.std(slow)
    # 运动学片段时长
    time = k - m
    # 怠速时间
    time_0 = n - m+1
    # 加速时间
    time_1 = len(plus)
    # 减速时间
    time_2 = len(slow)
    # 匀速时间
    time_3 = len(uniformity)
    # 怠速时间比
    ratio_0 = time_0/time
    # 加速时间比
    ratio_1 = time_1 / time
    # 减速时间比
    ratio_2 = time_2 / time
    # 匀速时间比
    ratio_3 = time_3 / time
   
    
    all = [v_average,v_average_travel,v_max,plus_average,slow_average,v_std,plus_std,slow_std,time,time_0,time_1,time_2,time_3,ratio_0,ratio_1,ratio_2,ratio_3]
    feature.append(all)

print("开始写入表格")
from pandas.core.frame import DataFrame
data=DataFrame(feature)
data.columns=["平均速度","平均行驶速度","最大速度","平均加速度","平均减速度","速度标准差","加速度标准差","减速度标准差","运动学片段时间长度","怠速时间","加速时间","减速时间","匀速时间","怠速时间比","加速时间比","减速时间比","匀速时间比"]  # 设置表头

data.to_excel('特征值二次改进C001803284019.xlsx',index=None)                          
data

开始计算特征值
开始写入表格

,平均速度,平均行驶速度,最大速度,平均加速度,平均减速度,速度标准差,加速度标准差,减速度标准差,运动学片段时间长度,怠速时间,加速时间,减速时间,匀速时间,怠速时间比,加速时间比,减速时间比,匀速时间比
0,0.064599,0.185185,0.555556,0.111111,-0.111111,0.142236,0.00000,0.000000,43,29,1,1,8,0.674419,0.023256,0.023256,0.186047
1,0.312500,0.312500,0.833333,0.125000,-0.107407,0.278423,0.01134,0.003024,20,1,3,3,9,0.050000,0.150000,0.150000,0.450000

In [194]:
import pandas as pd
import numpy as np
import xlsxwriter as xw

info = pd.read_excel("D:\jupyter notebook 保存文件\提取的运动学片段\运动学片段三次改进C001741703058.xlsx")
data1 = pd.DataFrame(info)
result = data1.values

excel = pd.read_excel("D:\jupyter notebook 保存文件\已经预处理的文件\预处理C001741703058.xlsx")
data2 = pd.DataFrame(excel)
data_a = data2.values  # 变为数组

print("开始计算特征值")
feature = []
#计算特征值
for i in range(len(result)):

    m = result[i][0]  # 运动学片段开始点
    n = result[i][1]  # 运动学片段怠速状态结束点
    k = result[i][2]+1  # 运动学片段结束点
    v_average = sum(data_a[m:k,9])/(k-m)#平均速度
    v_average_travel = sum(data_a[n:k,9])/(k-n)#平均行驶速度
    v_max = max(data_a[m:k,9])#最大速度
    #加减速
    plus = []#加速
    slow = []#减速
    uniformity = []#匀速
    for j in range(n+1,k):
        acc = data_a[j][10]#索引10为加速度
        v = data_a[j][9]
        if acc > 0.1:
            plus.append(acc)
        if acc < -0.1:
            slow.append(acc)
        if acc <= 0.1 and acc >= -0.1 and v !=0 :
            uniformity.append(acc)
    # 平均加速度
    if len(plus)==0:
        plus_average =0
    else:
        plus_average = sum(plus)/len(plus)
    # 平均减速度
    if len(slow)==0:
        slow_average =0
    else:
        slow_average = sum(slow)/len(slow)
    #slow_average = sum(slow)/len(slow)
    # 速度标准差
    v_std = np.std(data_a[m:k,9])
    # 加速度标准差
    plus_std = np.std(plus)
    # 减速度标准差
    slow_std = np.std(slow)
    # 运动学片段时长
    time = k - m
    # 怠速时间
    time_0 = n - m+1
    # 加速时间
    time_1 = len(plus)
    # 减速时间
    time_2 = len(slow)
    # 匀速时间
    time_3 = len(uniformity)
    # 怠速时间比
    ratio_0 = time_0/time
    # 加速时间比
    ratio_1 = time_1 / time
    # 减速时间比
    ratio_2 = time_2 / time
    # 匀速时间比
    ratio_3 = time_3 / time
   
    
    all = [v_average,v_average_travel,v_max,plus_average,slow_average,v_std,plus_std,slow_std,time,time_0,time_1,time_2,time_3,ratio_0,ratio_1,ratio_2,ratio_3]
    feature.append(all)

print("开始写入表格")
from pandas.core.frame import DataFrame
data=DataFrame(feature)
data.columns=["平均速度","平均行驶速度","最大速度","平均加速度","平均减速度","速度标准差","加速度标准差","减速度标准差","运动学片段时间长度","怠速时间","加速时间","减速时间","匀速时间","怠速时间比","加速时间比","减速时间比","匀速时间比"]  # 设置表头

data.to_excel('特征值二次改进C001741703058.xlsx',index=None)                          
data

开始计算特征值
开始写入表格

,平均速度,平均行驶速度,最大速度,平均加速度,平均减速度,速度标准差,加速度标准差,减速度标准差,运动学片段时间长度,怠速时间,加速时间,减速时间,匀速时间,怠速时间比,加速时间比,减速时间比,匀速时间比
0,0.044092,0.185185,0.555556,0.111111,-0.111111,0.121296,0.0,0.0,63,49,1,1,8,0.777778,0.015873,0.015873,0.126984

In [195]:
import pandas as pd
import numpy as np
import xlsxwriter as xw

info = pd.read_excel("D:\jupyter notebook 保存文件\提取的运动学片段\运动学片段三次改进C001257131007.xlsx")
data1 = pd.DataFrame(info)
result = data1.values

excel = pd.read_excel("D:\jupyter notebook 保存文件\已经预处理的文件\预处理C001257131007.xlsx")
data2 = pd.DataFrame(excel)
data_a = data2.values  # 变为数组

print("开始计算特征值")
feature = []
#计算特征值
for i in range(len(result)):

    m = result[i][0]  # 运动学片段开始点
    n = result[i][1]  # 运动学片段怠速状态结束点
    k = result[i][2]+1  # 运动学片段结束点
    v_average = sum(data_a[m:k,9])/(k-m)#平均速度
    v_average_travel = sum(data_a[n:k,9])/(k-n)#平均行驶速度
    v_max = max(data_a[m:k,9])#最大速度
    #加减速
    plus = []#加速
    slow = []#减速
    uniformity = []#匀速
    for j in range(n+1,k):
        acc = data_a[j][10]#索引10为加速度
        v = data_a[j][9]
        if acc > 0.1:
            plus.append(acc)
        if acc < -0.1:
            slow.append(acc)
        if acc <= 0.1 and acc >= -0.1 and v !=0 :
            uniformity.append(acc)
    # 平均加速度
    if len(plus)==0:
        plus_average =0
    else:
        plus_average = sum(plus)/len(plus)
    # 平均减速度
    if len(slow)==0:
        slow_average =0
    else:
        slow_average = sum(slow)/len(slow)
    #slow_average = sum(slow)/len(slow)
    # 速度标准差
    v_std = np.std(data_a[m:k,9])
    # 加速度标准差
    plus_std = np.std(plus)
    # 减速度标准差
    slow_std = np.std(slow)
    # 运动学片段时长
    time = k - m
    # 怠速时间
    time_0 = n - m+1
    # 加速时间
    time_1 = len(plus)
    # 减速时间
    time_2 = len(slow)
    # 匀速时间
    time_3 = len(uniformity)
    # 怠速时间比
    ratio_0 = time_0/time
    # 加速时间比
    ratio_1 = time_1 / time
    # 减速时间比
    ratio_2 = time_2 / time
    # 匀速时间比
    ratio_3 = time_3 / time
   
    
    all = [v_average,v_average_travel,v_max,plus_average,slow_average,v_std,plus_std,slow_std,time,time_0,time_1,time_2,time_3,ratio_0,ratio_1,ratio_2,ratio_3]
    feature.append(all)

print("开始写入表格")
from pandas.core.frame import DataFrame
data=DataFrame(feature)
data.columns=["平均速度","平均行驶速度","最大速度","平均加速度","平均减速度","速度标准差","加速度标准差","减速度标准差","运动学片段时间长度","怠速时间","加速时间","减速时间","匀速时间","怠速时间比","加速时间比","减速时间比","匀速时间比"]  # 设置表头

data.to_excel('特征值二次改进C001257131007.xlsx',index=None)                          
data

开始计算特征值
开始写入表格

,平均速度,平均行驶速度,最大速度,平均加速度,平均减速度,速度标准差,加速度标准差,减速度标准差,运动学片段时间长度,怠速时间,加速时间,减速时间,匀速时间,怠速时间比,加速时间比,减速时间比,匀速时间比
0,0.16835,0.308642,0.555556,0.111111,-0.111111,0.224102,0.0,0.0,33,16,1,1,13,0.484848,0.030303,0.030303,0.393939

In [196]:
import pandas as pd
import numpy as np
import xlsxwriter as xw

info = pd.read_excel("D:\jupyter notebook 保存文件\提取的运动学片段\运动学片段三次改进C001623817201.xlsx")
data1 = pd.DataFrame(info)
result = data1.values

excel = pd.read_excel("D:\jupyter notebook 保存文件\已经预处理的文件\预处理C001623817201.xlsx")
data2 = pd.DataFrame(excel)
data_a = data2.values  # 变为数组

print("开始计算特征值")
feature = []
#计算特征值
for i in range(len(result)):

    m = result[i][0]  # 运动学片段开始点
    n = result[i][1]  # 运动学片段怠速状态结束点
    k = result[i][2]+1  # 运动学片段结束点
    v_average = sum(data_a[m:k,9])/(k-m)#平均速度
    v_average_travel = sum(data_a[n:k,9])/(k-n)#平均行驶速度
    v_max = max(data_a[m:k,9])#最大速度
    #加减速
    plus = []#加速
    slow = []#减速
    uniformity = []#匀速
    for j in range(n+1,k):
        acc = data_a[j][10]#索引10为加速度
        v = data_a[j][9]
        if acc > 0.1:
            plus.append(acc)
        if acc < -0.1:
            slow.append(acc)
        if acc <= 0.1 and acc >= -0.1 and v !=0 :
            uniformity.append(acc)
    # 平均加速度
    if len(plus)==0:
        plus_average =0
    else:
        plus_average = sum(plus)/len(plus)
    # 平均减速度
    if len(slow)==0:
        slow_average =0
    else:
        slow_average = sum(slow)/len(slow)
    #slow_average = sum(slow)/len(slow)
    # 速度标准差
    v_std = np.std(data_a[m:k,9])
    # 加速度标准差
    plus_std = np.std(plus)
    # 减速度标准差
    slow_std = np.std(slow)
    # 运动学片段时长
    time = k - m
    # 怠速时间
    time_0 = n - m+1
    # 加速时间
    time_1 = len(plus)
    # 减速时间
    time_2 = len(slow)
    # 匀速时间
    time_3 = len(uniformity)
    # 怠速时间比
    ratio_0 = time_0/time
    # 加速时间比
    ratio_1 = time_1 / time
    # 减速时间比
    ratio_2 = time_2 / time
    # 匀速时间比
    ratio_3 = time_3 / time
   
    
    all = [v_average,v_average_travel,v_max,plus_average,slow_average,v_std,plus_std,slow_std,time,time_0,time_1,time_2,time_3,ratio_0,ratio_1,ratio_2,ratio_3]
    feature.append(all)

print("开始写入表格")
from pandas.core.frame import DataFrame
data=DataFrame(feature)
data.columns=["平均速度","平均行驶速度","最大速度","平均加速度","平均减速度","速度标准差","加速度标准差","减速度标准差","运动学片段时间长度","怠速时间","加速时间","减速时间","匀速时间","怠速时间比","加速时间比","减速时间比","匀速时间比"]  # 设置表头

data.to_excel('特征值二次改进C001623817201.xlsx',index=None)                          
data

开始计算特征值
开始写入表格

,平均速度,平均行驶速度,最大速度,平均加速度,平均减速度,速度标准差,加速度标准差,减速度标准差,运动学片段时间长度,怠速时间,加速时间,减速时间,匀速时间,怠速时间比,加速时间比,减速时间比,匀速时间比
0,0.041254,0.378788,0.833333,0.15,-0.166667,0.147226,0.016667,0.0,101,91,2,1,7,0.90099,0.019802,0.009901,0.069307

In [197]:
import pandas as pd
import numpy as np
import xlsxwriter as xw

info = pd.read_excel("D:\jupyter notebook 保存文件\提取的运动学片段\运动学片段三次改进C001892910129.xlsx")
data1 = pd.DataFrame(info)
result = data1.values

excel = pd.read_excel("D:\jupyter notebook 保存文件\已经预处理的文件\预处理C001892910129.xlsx")
data2 = pd.DataFrame(excel)
data_a = data2.values  # 变为数组

print("开始计算特征值")
feature = []
#计算特征值
for i in range(len(result)):

    m = result[i][0]  # 运动学片段开始点
    n = result[i][1]  # 运动学片段怠速状态结束点
    k = result[i][2]+1  # 运动学片段结束点
    v_average = sum(data_a[m:k,9])/(k-m)#平均速度
    v_average_travel = sum(data_a[n:k,9])/(k-n)#平均行驶速度
    v_max = max(data_a[m:k,9])#最大速度
    #加减速
    plus = []#加速
    slow = []#减速
    uniformity = []#匀速
    for j in range(n+1,k):
        acc = data_a[j][10]#索引10为加速度
        v = data_a[j][9]
        if acc > 0.1:
            plus.append(acc)
        if acc < -0.1:
            slow.append(acc)
        if acc <= 0.1 and acc >= -0.1 and v !=0 :
            uniformity.append(acc)
    # 平均加速度
    if len(plus)==0:
        plus_average =0
    else:
        plus_average = sum(plus)/len(plus)
    # 平均减速度
    if len(slow)==0:
        slow_average =0
    else:
        slow_average = sum(slow)/len(slow)
    #slow_average = sum(slow)/len(slow)
    # 速度标准差
    v_std = np.std(data_a[m:k,9])
    # 加速度标准差
    plus_std = np.std(plus)
    # 减速度标准差
    slow_std = np.std(slow)
    # 运动学片段时长
    time = k - m
    # 怠速时间
    time_0 = n - m+1
    # 加速时间
    time_1 = len(plus)
    # 减速时间
    time_2 = len(slow)
    # 匀速时间
    time_3 = len(uniformity)
    # 怠速时间比
    ratio_0 = time_0/time
    # 加速时间比
    ratio_1 = time_1 / time
    # 减速时间比
    ratio_2 = time_2 / time
    # 匀速时间比
    ratio_3 = time_3 / time
   
    
    all = [v_average,v_average_travel,v_max,plus_average,slow_average,v_std,plus_std,slow_std,time,time_0,time_1,time_2,time_3,ratio_0,ratio_1,ratio_2,ratio_3]
    feature.append(all)

print("开始写入表格")
from pandas.core.frame import DataFrame
data=DataFrame(feature)
data.columns=["平均速度","平均行驶速度","最大速度","平均加速度","平均减速度","速度标准差","加速度标准差","减速度标准差","运动学片段时间长度","怠速时间","加速时间","减速时间","匀速时间","怠速时间比","加速时间比","减速时间比","匀速时间比"]  # 设置表头

data.to_excel('特征值二次改进C001892910129.xlsx',index=None)                          
data

开始计算特征值
开始写入表格

,平均速度,平均行驶速度,最大速度,平均加速度,平均减速度,速度标准差,加速度标准差,减速度标准差,运动学片段时间长度,怠速时间,加速时间,减速时间,匀速时间,怠速时间比,加速时间比,减速时间比,匀速时间比
0,1.127778,1.87963,3.333333,0.453869,-0.251736,1.118772,0.21831,0.071171,25,11,7,4,3,0.44,0.28,0.16,0.12

In [198]:
import pandas as pd
import numpy as np
import xlsxwriter as xw

info = pd.read_excel("D:\jupyter notebook 保存文件\提取的运动学片段\运动学片段三次改进C001381821019.xlsx")
data1 = pd.DataFrame(info)
result = data1.values

excel = pd.read_excel("D:\jupyter notebook 保存文件\已经预处理的文件\预处理C001381821019.xlsx")
data2 = pd.DataFrame(excel)
data_a = data2.values  # 变为数组

print("开始计算特征值")
feature = []
#计算特征值
for i in range(len(result)):

    m = result[i][0]  # 运动学片段开始点
    n = result[i][1]  # 运动学片段怠速状态结束点
    k = result[i][2]+1  # 运动学片段结束点
    v_average = sum(data_a[m:k,9])/(k-m)#平均速度
    v_average_travel = sum(data_a[n:k,9])/(k-n)#平均行驶速度
    v_max = max(data_a[m:k,9])#最大速度
    #加减速
    plus = []#加速
    slow = []#减速
    uniformity = []#匀速
    for j in range(n+1,k):
        acc = data_a[j][10]#索引10为加速度
        v = data_a[j][9]
        if acc > 0.1:
            plus.append(acc)
        if acc < -0.1:
            slow.append(acc)
        if acc <= 0.1 and acc >= -0.1 and v !=0 :
            uniformity.append(acc)
    # 平均加速度
    if len(plus)==0:
        plus_average =0
    else:
        plus_average = sum(plus)/len(plus)
    # 平均减速度
    if len(slow)==0:
        slow_average =0
    else:
        slow_average = sum(slow)/len(slow)
    #slow_average = sum(slow)/len(slow)
    # 速度标准差
    v_std = np.std(data_a[m:k,9])
    # 加速度标准差
    plus_std = np.std(plus)
    # 减速度标准差
    slow_std = np.std(slow)
    # 运动学片段时长
    time = k - m
    # 怠速时间
    time_0 = n - m+1
    # 加速时间
    time_1 = len(plus)
    # 减速时间
    time_2 = len(slow)
    # 匀速时间
    time_3 = len(uniformity)
    # 怠速时间比
    ratio_0 = time_0/time
    # 加速时间比
    ratio_1 = time_1 / time
    # 减速时间比
    ratio_2 = time_2 / time
    # 匀速时间比
    ratio_3 = time_3 / time
   
    
    all = [v_average,v_average_travel,v_max,plus_average,slow_average,v_std,plus_std,slow_std,time,time_0,time_1,time_2,time_3,ratio_0,ratio_1,ratio_2,ratio_3]
    feature.append(all)

print("开始写入表格")
from pandas.core.frame import DataFrame
data=DataFrame(feature)
data.columns=["平均速度","平均行驶速度","最大速度","平均加速度","平均减速度","速度标准差","加速度标准差","减速度标准差","运动学片段时间长度","怠速时间","加速时间","减速时间","匀速时间","怠速时间比","加速时间比","减速时间比","匀速时间比"]  # 设置表头

data.to_excel('特征值二次改进C001381821019.xlsx',index=None)                          
data

开始计算特征值
开始写入表格

,平均速度,平均行驶速度,最大速度,平均加速度,平均减速度,速度标准差,加速度标准差,减速度标准差,运动学片段时间长度,怠速时间,加速时间,减速时间,匀速时间,怠速时间比,加速时间比,减速时间比,匀速时间比
0,0.281746,0.394444,0.833333,0.111111,-0.144444,0.298689,0.0,0.015713,35,11,1,3,17,0.314286,0.028571,0.085714,0.485714

In [199]:
import pandas as pd
import numpy as np
import xlsxwriter as xw

info = pd.read_excel("D:\jupyter notebook 保存文件\提取的运动学片段\运动学片段三次改进C001549510090.xlsx")
data1 = pd.DataFrame(info)
result = data1.values

excel = pd.read_excel("D:\jupyter notebook 保存文件\已经预处理的文件\预处理C001549510090.xlsx")
data2 = pd.DataFrame(excel)
data_a = data2.values  # 变为数组

print("开始计算特征值")
feature = []
#计算特征值
for i in range(len(result)):

    m = result[i][0]  # 运动学片段开始点
    n = result[i][1]  # 运动学片段怠速状态结束点
    k = result[i][2]+1  # 运动学片段结束点
    v_average = sum(data_a[m:k,9])/(k-m)#平均速度
    v_average_travel = sum(data_a[n:k,9])/(k-n)#平均行驶速度
    v_max = max(data_a[m:k,9])#最大速度
    #加减速
    plus = []#加速
    slow = []#减速
    uniformity = []#匀速
    for j in range(n+1,k):
        acc = data_a[j][10]#索引10为加速度
        v = data_a[j][9]
        if acc > 0.1:
            plus.append(acc)
        if acc < -0.1:
            slow.append(acc)
        if acc <= 0.1 and acc >= -0.1 and v !=0 :
            uniformity.append(acc)
    # 平均加速度
    if len(plus)==0:
        plus_average =0
    else:
        plus_average = sum(plus)/len(plus)
    # 平均减速度
    if len(slow)==0:
        slow_average =0
    else:
        slow_average = sum(slow)/len(slow)
    #slow_average = sum(slow)/len(slow)
    # 速度标准差
    v_std = np.std(data_a[m:k,9])
    # 加速度标准差
    plus_std = np.std(plus)
    # 减速度标准差
    slow_std = np.std(slow)
    # 运动学片段时长
    time = k - m
    # 怠速时间
    time_0 = n - m+1
    # 加速时间
    time_1 = len(plus)
    # 减速时间
    time_2 = len(slow)
    # 匀速时间
    time_3 = len(uniformity)
    # 怠速时间比
    ratio_0 = time_0/time
    # 加速时间比
    ratio_1 = time_1 / time
    # 减速时间比
    ratio_2 = time_2 / time
    # 匀速时间比
    ratio_3 = time_3 / time
   
    
    all = [v_average,v_average_travel,v_max,plus_average,slow_average,v_std,plus_std,slow_std,time,time_0,time_1,time_2,time_3,ratio_0,ratio_1,ratio_2,ratio_3]
    feature.append(all)

print("开始写入表格")
from pandas.core.frame import DataFrame
data=DataFrame(feature)
data.columns=["平均速度","平均行驶速度","最大速度","平均加速度","平均减速度","速度标准差","加速度标准差","减速度标准差","运动学片段时间长度","怠速时间","加速时间","减速时间","匀速时间","怠速时间比","加速时间比","减速时间比","匀速时间比"]  # 设置表头

data.to_excel('特征值二次改进C001549510090.xlsx',index=None)                          
data

开始计算特征值
开始写入表格

,平均速度,平均行驶速度,最大速度,平均加速度,平均减速度,速度标准差,加速度标准差,减速度标准差,运动学片段时间长度,怠速时间,加速时间,减速时间,匀速时间,怠速时间比,加速时间比,减速时间比,匀速时间比
0,0.03268,0.185185,0.555556,0.111111,-0.111111,0.106197,0.0,0.0,85,71,1,1,8,0.835294,0.011765,0.011765,0.094118

In [200]:
import pandas as pd
import numpy as np
import xlsxwriter as xw

info = pd.read_excel("D:\jupyter notebook 保存文件\提取的运动学片段\运动学片段三次改进C001827963302.xlsx")
data1 = pd.DataFrame(info)
result = data1.values

excel = pd.read_excel("D:\jupyter notebook 保存文件\已经预处理的文件\预处理C001827963302.xlsx")
data2 = pd.DataFrame(excel)
data_a = data2.values  # 变为数组

print("开始计算特征值")
feature = []
#计算特征值
for i in range(len(result)):

    m = result[i][0]  # 运动学片段开始点
    n = result[i][1]  # 运动学片段怠速状态结束点
    k = result[i][2]+1  # 运动学片段结束点
    v_average = sum(data_a[m:k,9])/(k-m)#平均速度
    v_average_travel = sum(data_a[n:k,9])/(k-n)#平均行驶速度
    v_max = max(data_a[m:k,9])#最大速度
    #加减速
    plus = []#加速
    slow = []#减速
    uniformity = []#匀速
    for j in range(n+1,k):
        acc = data_a[j][10]#索引10为加速度
        v = data_a[j][9]
        if acc > 0.1:
            plus.append(acc)
        if acc < -0.1:
            slow.append(acc)
        if acc <= 0.1 and acc >= -0.1 and v !=0 :
            uniformity.append(acc)
    # 平均加速度
    if len(plus)==0:
        plus_average =0
    else:
        plus_average = sum(plus)/len(plus)
    # 平均减速度
    if len(slow)==0:
        slow_average =0
    else:
        slow_average = sum(slow)/len(slow)
    #slow_average = sum(slow)/len(slow)
    # 速度标准差
    v_std = np.std(data_a[m:k,9])
    # 加速度标准差
    plus_std = np.std(plus)
    # 减速度标准差
    slow_std = np.std(slow)
    # 运动学片段时长
    time = k - m
    # 怠速时间
    time_0 = n - m+1
    # 加速时间
    time_1 = len(plus)
    # 减速时间
    time_2 = len(slow)
    # 匀速时间
    time_3 = len(uniformity)
    # 怠速时间比
    ratio_0 = time_0/time
    # 加速时间比
    ratio_1 = time_1 / time
    # 减速时间比
    ratio_2 = time_2 / time
    # 匀速时间比
    ratio_3 = time_3 / time
   
    
    all = [v_average,v_average_travel,v_max,plus_average,slow_average,v_std,plus_std,slow_std,time,time_0,time_1,time_2,time_3,ratio_0,ratio_1,ratio_2,ratio_3]
    feature.append(all)

print("开始写入表格")
from pandas.core.frame import DataFrame
data=DataFrame(feature)
data.columns=["平均速度","平均行驶速度","最大速度","平均加速度","平均减速度","速度标准差","加速度标准差","减速度标准差","运动学片段时间长度","怠速时间","加速时间","减速时间","匀速时间","怠速时间比","加速时间比","减速时间比","匀速时间比"]  # 设置表头

data.to_excel('特征值二次改进C001827963302.xlsx',index=None)                          
data

开始计算特征值
开始写入表格

,平均速度,平均行驶速度,最大速度,平均加速度,平均减速度,速度标准差,加速度标准差,减速度标准差,运动学片段时间长度,怠速时间,加速时间,减速时间,匀速时间,怠速时间比,加速时间比,减速时间比,匀速时间比
0,0.079365,0.185185,0.555556,0.111111,-0.111111,0.153895,0.0,0.0,35,21,1,1,8,0.6,0.028571,0.028571,0.228571

In [201]:
import pandas as pd
import numpy as np
import xlsxwriter as xw

info = pd.read_excel("D:\jupyter notebook 保存文件\提取的运动学片段\运动学片段三次改进C001667458806.xlsx")
data1 = pd.DataFrame(info)
result = data1.values

excel = pd.read_excel("D:\jupyter notebook 保存文件\已经预处理的文件\预处理C001667458806.xlsx")
data2 = pd.DataFrame(excel)
data_a = data2.values  # 变为数组

print("开始计算特征值")
feature = []
#计算特征值
for i in range(len(result)):

    m = result[i][0]  # 运动学片段开始点
    n = result[i][1]  # 运动学片段怠速状态结束点
    k = result[i][2]+1  # 运动学片段结束点
    v_average = sum(data_a[m:k,9])/(k-m)#平均速度
    v_average_travel = sum(data_a[n:k,9])/(k-n)#平均行驶速度
    v_max = max(data_a[m:k,9])#最大速度
    #加减速
    plus = []#加速
    slow = []#减速
    uniformity = []#匀速
    for j in range(n+1,k):
        acc = data_a[j][10]#索引10为加速度
        v = data_a[j][9]
        if acc > 0.1:
            plus.append(acc)
        if acc < -0.1:
            slow.append(acc)
        if acc <= 0.1 and acc >= -0.1 and v !=0 :
            uniformity.append(acc)
    # 平均加速度
    if len(plus)==0:
        plus_average =0
    else:
        plus_average = sum(plus)/len(plus)
    # 平均减速度
    if len(slow)==0:
        slow_average =0
    else:
        slow_average = sum(slow)/len(slow)
    #slow_average = sum(slow)/len(slow)
    # 速度标准差
    v_std = np.std(data_a[m:k,9])
    # 加速度标准差
    plus_std = np.std(plus)
    # 减速度标准差
    slow_std = np.std(slow)
    # 运动学片段时长
    time = k - m
    # 怠速时间
    time_0 = n - m+1
    # 加速时间
    time_1 = len(plus)
    # 减速时间
    time_2 = len(slow)
    # 匀速时间
    time_3 = len(uniformity)
    # 怠速时间比
    ratio_0 = time_0/time
    # 加速时间比
    ratio_1 = time_1 / time
    # 减速时间比
    ratio_2 = time_2 / time
    # 匀速时间比
    ratio_3 = time_3 / time
   
    
    all = [v_average,v_average_travel,v_max,plus_average,slow_average,v_std,plus_std,slow_std,time,time_0,time_1,time_2,time_3,ratio_0,ratio_1,ratio_2,ratio_3]
    feature.append(all)

print("开始写入表格")
from pandas.core.frame import DataFrame
data=DataFrame(feature)
data.columns=["平均速度","平均行驶速度","最大速度","平均加速度","平均减速度","速度标准差","加速度标准差","减速度标准差","运动学片段时间长度","怠速时间","加速时间","减速时间","匀速时间","怠速时间比","加速时间比","减速时间比","匀速时间比"]  # 设置表头

data.to_excel('特征值二次改进C001667458806.xlsx',index=None)                          
data

开始计算特征值
开始写入表格

,平均速度,平均行驶速度,最大速度,平均加速度,平均减速度,速度标准差,加速度标准差,减速度标准差,运动学片段时间长度,怠速时间,加速时间,减速时间,匀速时间,怠速时间比,加速时间比,减速时间比,匀速时间比
0,0.179487,0.466667,1.388889,0.407407,-0.194444,0.335749,0.308765,0.133854,65,41,3,11,6,0.630769,0.046154,0.169231,0.092308

In [186]:
import pandas as pd
import numpy as np
import xlsxwriter as xw

info = pd.read_excel("D:\jupyter notebook 保存文件\提取的运动学片段\运动学片段三次改进C001934049097.xlsx")
data1 = pd.DataFrame(info)
result = data1.values

excel = pd.read_excel("D:\jupyter notebook 保存文件\已经预处理的文件\预处理C001934049097.xlsx")
data2 = pd.DataFrame(excel)
data_a = data2.values  # 变为数组

print("开始计算特征值")
feature = []
#计算特征值
for i in range(len(result)):

    m = result[i][0]  # 运动学片段开始点
    n = result[i][1]  # 运动学片段怠速状态结束点
    k = result[i][2]+1  # 运动学片段结束点
    v_average = sum(data_a[m:k,9])/(k-m)#平均速度
    v_average_travel = sum(data_a[n:k,9])/(k-n)#平均行驶速度
    v_max = max(data_a[m:k,9])#最大速度
    #加减速
    plus = []#加速
    slow = []#减速
    uniformity = []#匀速
    for j in range(n+1,k):
        acc = data_a[j][10]#索引10为加速度
        v = data_a[j][9]
        if acc > 0.1:
            plus.append(acc)
        if acc < -0.1:
            slow.append(acc)
        if acc <= 0.1 and acc >= -0.1 and v !=0 :
            uniformity.append(acc)
    # 平均加速度
    if len(plus)==0:
        plus_average =0
    else:
        plus_average = sum(plus)/len(plus)
    # 平均减速度
    if len(slow)==0:
        slow_average =0
    else:
        slow_average = sum(slow)/len(slow)
    #slow_average = sum(slow)/len(slow)
    # 速度标准差
    v_std = np.std(data_a[m:k,9])
    # 加速度标准差
    plus_std = np.std(plus)
    # 减速度标准差
    slow_std = np.std(slow)
    # 运动学片段时长
    time = k - m
    # 怠速时间
    time_0 = n - m+1
    # 加速时间
    time_1 = len(plus)
    # 减速时间
    time_2 = len(slow)
    # 匀速时间
    time_3 = len(uniformity)
    # 怠速时间比
    ratio_0 = time_0/time
    # 加速时间比
    ratio_1 = time_1 / time
    # 减速时间比
    ratio_2 = time_2 / time
    # 匀速时间比
    ratio_3 = time_3 / time
   
    
    all = [v_average,v_average_travel,v_max,plus_average,slow_average,v_std,plus_std,slow_std,time,time_0,time_1,time_2,time_3,ratio_0,ratio_1,ratio_2,ratio_3]
    feature.append(all)

print("开始写入表格")
from pandas.core.frame import DataFrame
data=DataFrame(feature)
data.columns=["平均速度","平均行驶速度","最大速度","平均加速度","平均减速度","速度标准差","加速度标准差","减速度标准差","运动学片段时间长度","怠速时间","加速时间","减速时间","匀速时间","怠速时间比","加速时间比","减速时间比","匀速时间比"]  # 设置表头

data.to_excel('特征值二次改进C001934049097.xlsx',index=None)                          
data

开始计算特征值
开始写入表格

,平均速度,平均行驶速度,最大速度,平均加速度,平均减速度,速度标准差,加速度标准差,减速度标准差,运动学片段时间长度,怠速时间,加速时间,减速时间,匀速时间,怠速时间比,加速时间比,减速时间比,匀速时间比
0,0.373428,0.460271,1.111111,0.111111,-0.146032,0.306800,0.000000,0.039139,106,21,4,7,70,0.198113,0.037736,0.066038,0.660377
1,0.242063,0.564815,1.388889,0.393519,-0.309524,0.466401,0.142695,0.149371,35,21,3,7,3,0.600000,0.085714,0.200000,0.085714
2,0.185185,0.277778,0.555556,0.111111,-0.111111,0.228312,0.000000,0.000000,30,11,1,1,13,0.366667,0.033333,0.033333,0.433333

In [187]:
import pandas as pd
import numpy as np
import xlsxwriter as xw

info = pd.read_excel("D:\jupyter notebook 保存文件\提取的运动学片段\运动学片段三次改进C001194657151.xlsx")
data1 = pd.DataFrame(info)
result = data1.values

excel = pd.read_excel("D:\jupyter notebook 保存文件\已经预处理的文件\预处理C001194657151.xlsx")
data2 = pd.DataFrame(excel)
data_a = data2.values  # 变为数组

print("开始计算特征值")
feature = []
#计算特征值
for i in range(len(result)):

    m = result[i][0]  # 运动学片段开始点
    n = result[i][1]  # 运动学片段怠速状态结束点
    k = result[i][2]+1  # 运动学片段结束点
    v_average = sum(data_a[m:k,9])/(k-m)#平均速度
    v_average_travel = sum(data_a[n:k,9])/(k-n)#平均行驶速度
    v_max = max(data_a[m:k,9])#最大速度
    #加减速
    plus = []#加速
    slow = []#减速
    uniformity = []#匀速
    for j in range(n+1,k):
        acc = data_a[j][10]#索引10为加速度
        v = data_a[j][9]
        if acc > 0.1:
            plus.append(acc)
        if acc < -0.1:
            slow.append(acc)
        if acc <= 0.1 and acc >= -0.1 and v !=0 :
            uniformity.append(acc)
    # 平均加速度
    if len(plus)==0:
        plus_average =0
    else:
        plus_average = sum(plus)/len(plus)
    # 平均减速度
    if len(slow)==0:
        slow_average =0
    else:
        slow_average = sum(slow)/len(slow)
    #slow_average = sum(slow)/len(slow)
    # 速度标准差
    v_std = np.std(data_a[m:k,9])
    # 加速度标准差
    plus_std = np.std(plus)
    # 减速度标准差
    slow_std = np.std(slow)
    # 运动学片段时长
    time = k - m
    # 怠速时间
    time_0 = n - m+1
    # 加速时间
    time_1 = len(plus)
    # 减速时间
    time_2 = len(slow)
    # 匀速时间
    time_3 = len(uniformity)
    # 怠速时间比
    ratio_0 = time_0/time
    # 加速时间比
    ratio_1 = time_1 / time
    # 减速时间比
    ratio_2 = time_2 / time
    # 匀速时间比
    ratio_3 = time_3 / time
   
    
    all = [v_average,v_average_travel,v_max,plus_average,slow_average,v_std,plus_std,slow_std,time,time_0,time_1,time_2,time_3,ratio_0,ratio_1,ratio_2,ratio_3]
    feature.append(all)

print("开始写入表格")
from pandas.core.frame import DataFrame
data=DataFrame(feature)
data.columns=["平均速度","平均行驶速度","最大速度","平均加速度","平均减速度","速度标准差","加速度标准差","减速度标准差","运动学片段时间长度","怠速时间","加速时间","减速时间","匀速时间","怠速时间比","加速时间比","减速时间比","匀速时间比"]  # 设置表头

data.to_excel('特征值二次改进C001194657151.xlsx',index=None)                          
data

开始计算特征值
开始写入表格

,平均速度,平均行驶速度,最大速度,平均加速度,平均减速度,速度标准差,加速度标准差,减速度标准差,运动学片段时间长度,怠速时间,加速时间,减速时间,匀速时间,怠速时间比,加速时间比,减速时间比,匀速时间比
0,0.222222,0.222222,0.555556,0.111111,-0.111111,0.185924,0.000000,0.0,25,1,2,2,16,0.040000,0.080000,0.080000,0.64
1,0.069444,0.185185,0.555556,0.111111,-0.111111,0.146329,0.000000,0.0,40,26,1,1,8,0.650000,0.025000,0.025000,0.20
2,0.300000,0.450000,0.833333,0.127778,-0.111111,0.302043,0.022906,0.0,75,26,4,2,39,0.346667,0.053333,0.026667,0.52

In [188]:
import pandas as pd
import numpy as np
import xlsxwriter as xw

info = pd.read_excel("D:\jupyter notebook 保存文件\提取的运动学片段\运动学片段三次改进C001584910144.xlsx")
data1 = pd.DataFrame(info)
result = data1.values

excel = pd.read_excel("D:\jupyter notebook 保存文件\已经预处理的文件\预处理C001584910144.xlsx")
data2 = pd.DataFrame(excel)
data_a = data2.values  # 变为数组

print("开始计算特征值")
feature = []
#计算特征值
for i in range(len(result)):

    m = result[i][0]  # 运动学片段开始点
    n = result[i][1]  # 运动学片段怠速状态结束点
    k = result[i][2]+1  # 运动学片段结束点
    v_average = sum(data_a[m:k,9])/(k-m)#平均速度
    v_average_travel = sum(data_a[n:k,9])/(k-n)#平均行驶速度
    v_max = max(data_a[m:k,9])#最大速度
    #加减速
    plus = []#加速
    slow = []#减速
    uniformity = []#匀速
    for j in range(n+1,k):
        acc = data_a[j][10]#索引10为加速度
        v = data_a[j][9]
        if acc > 0.1:
            plus.append(acc)
        if acc < -0.1:
            slow.append(acc)
        if acc <= 0.1 and acc >= -0.1 and v !=0 :
            uniformity.append(acc)
    # 平均加速度
    if len(plus)==0:
        plus_average =0
    else:
        plus_average = sum(plus)/len(plus)
    # 平均减速度
    if len(slow)==0:
        slow_average =0
    else:
        slow_average = sum(slow)/len(slow)
    #slow_average = sum(slow)/len(slow)
    # 速度标准差
    v_std = np.std(data_a[m:k,9])
    # 加速度标准差
    plus_std = np.std(plus)
    # 减速度标准差
    slow_std = np.std(slow)
    # 运动学片段时长
    time = k - m
    # 怠速时间
    time_0 = n - m+1
    # 加速时间
    time_1 = len(plus)
    # 减速时间
    time_2 = len(slow)
    # 匀速时间
    time_3 = len(uniformity)
    # 怠速时间比
    ratio_0 = time_0/time
    # 加速时间比
    ratio_1 = time_1 / time
    # 减速时间比
    ratio_2 = time_2 / time
    # 匀速时间比
    ratio_3 = time_3 / time
   
    
    all = [v_average,v_average_travel,v_max,plus_average,slow_average,v_std,plus_std,slow_std,time,time_0,time_1,time_2,time_3,ratio_0,ratio_1,ratio_2,ratio_3]
    feature.append(all)

print("开始写入表格")
from pandas.core.frame import DataFrame
data=DataFrame(feature)
data.columns=["平均速度","平均行驶速度","最大速度","平均加速度","平均减速度","速度标准差","加速度标准差","减速度标准差","运动学片段时间长度","怠速时间","加速时间","减速时间","匀速时间","怠速时间比","加速时间比","减速时间比","匀速时间比"]  # 设置表头

data.to_excel('特征值二次改进C001584910144.xlsx',index=None)                          
data

开始计算特征值
开始写入表格

,平均速度,平均行驶速度,最大速度,平均加速度,平均减速度,速度标准差,加速度标准差,减速度标准差,运动学片段时间长度,怠速时间,加速时间,减速时间,匀速时间,怠速时间比,加速时间比,减速时间比,匀速时间比
0,0.222222,0.277778,0.555556,0.111111,-0.111111,0.233069,0.000000,0.000000,25,6,1,1,13,0.240000,0.040000,0.040000,0.520000
1,0.305011,0.338164,0.833333,0.137037,-0.125000,0.238576,0.022831,0.024056,51,6,3,4,34,0.117647,0.058824,0.078431,0.666667
2,0.185185,0.185185,0.555556,0.111111,-0.111111,0.188853,0.000000,0.000000,15,1,1,1,8,0.066667,0.066667,0.066667,0.533333

In [189]:
import pandas as pd
import numpy as np
import xlsxwriter as xw

info = pd.read_excel("D:\jupyter notebook 保存文件\提取的运动学片段\运动学片段三次改进C001354436144.xlsx")
data1 = pd.DataFrame(info)
result = data1.values

excel = pd.read_excel("D:\jupyter notebook 保存文件\已经预处理的文件\预处理C001354436144.xlsx")
data2 = pd.DataFrame(excel)
data_a = data2.values  # 变为数组

print("开始计算特征值")
feature = []
#计算特征值
for i in range(len(result)):

    m = result[i][0]  # 运动学片段开始点
    n = result[i][1]  # 运动学片段怠速状态结束点
    k = result[i][2]+1  # 运动学片段结束点
    v_average = sum(data_a[m:k,9])/(k-m)#平均速度
    v_average_travel = sum(data_a[n:k,9])/(k-n)#平均行驶速度
    v_max = max(data_a[m:k,9])#最大速度
    #加减速
    plus = []#加速
    slow = []#减速
    uniformity = []#匀速
    for j in range(n+1,k):
        acc = data_a[j][10]#索引10为加速度
        v = data_a[j][9]
        if acc > 0.1:
            plus.append(acc)
        if acc < -0.1:
            slow.append(acc)
        if acc <= 0.1 and acc >= -0.1 and v !=0 :
            uniformity.append(acc)
    # 平均加速度
    if len(plus)==0:
        plus_average =0
    else:
        plus_average = sum(plus)/len(plus)
    # 平均减速度
    if len(slow)==0:
        slow_average =0
    else:
        slow_average = sum(slow)/len(slow)
    #slow_average = sum(slow)/len(slow)
    # 速度标准差
    v_std = np.std(data_a[m:k,9])
    # 加速度标准差
    plus_std = np.std(plus)
    # 减速度标准差
    slow_std = np.std(slow)
    # 运动学片段时长
    time = k - m
    # 怠速时间
    time_0 = n - m+1
    # 加速时间
    time_1 = len(plus)
    # 减速时间
    time_2 = len(slow)
    # 匀速时间
    time_3 = len(uniformity)
    # 怠速时间比
    ratio_0 = time_0/time
    # 加速时间比
    ratio_1 = time_1 / time
    # 减速时间比
    ratio_2 = time_2 / time
    # 匀速时间比
    ratio_3 = time_3 / time
   
    
    all = [v_average,v_average_travel,v_max,plus_average,slow_average,v_std,plus_std,slow_std,time,time_0,time_1,time_2,time_3,ratio_0,ratio_1,ratio_2,ratio_3]
    feature.append(all)

print("开始写入表格")
from pandas.core.frame import DataFrame
data=DataFrame(feature)
data.columns=["平均速度","平均行驶速度","最大速度","平均加速度","平均减速度","速度标准差","加速度标准差","减速度标准差","运动学片段时间长度","怠速时间","加速时间","减速时间","匀速时间","怠速时间比","加速时间比","减速时间比","匀速时间比"]  # 设置表头

data.to_excel('特征值二次改进C001354436144.xlsx',index=None)                          
data

开始计算特征值
开始写入表格

,平均速度,平均行驶速度,最大速度,平均加速度,平均减速度,速度标准差,加速度标准差,减速度标准差,运动学片段时间长度,怠速时间,加速时间,减速时间,匀速时间,怠速时间比,加速时间比,减速时间比,匀速时间比
0,0.138889,0.185185,0.555556,0.111111,-0.111111,0.182151,0.000000,0.000000,20,6,1,1,8,0.300000,0.050000,0.050000,0.400000
1,0.416667,0.416667,1.111111,0.201389,-0.263889,0.386234,0.077018,0.094540,18,1,4,6,6,0.055556,0.222222,0.333333,0.333333
2,0.539683,0.539683,1.388889,0.166667,-0.218056,0.370559,0.078567,0.049359,35,1,3,8,20,0.028571,0.085714,0.228571,0.571429

In [ ]:
[0.833333333333333, 1.04166666666667, 1.25]

In [1]:

print("开始计算特征值")
feature = []
#计算特征值
for i in range(len(result)):
    m = result[i][0]  # 运动学片段开始点
    n = result[i][1]  # 运动学片段怠速状态结束点
    k = result[i][2]+1  # 运动学片段结束点
    v_average = sum(data_a[m:k,9])/(k-m)#平均速度
    v_average_travel = sum(data_a[n:k,9])/(k-n)#平均行驶速度
    v_max = max(data_a[m:k,9])#最大速度
    #加减速
    plus = []#加速
    slow = []#减速
    uniformity = []#匀速
    for j in range(m,k):
        acc = data_a[j][10]#索引10为加速度
        if acc > 0:
            plus.append(acc)
        if acc < 0:
            slow.append(acc)
        if acc == 0:
            uniformity.append(acc)
    i+=1

开始计算特征值

In [1]:
import pandas as pd
import numpy as np
import xlsxwriter as xw

info = pd.read_excel("D:\jupyter notebook 保存文件\运动学片段二次改进21UEE92Q.xlsx")
data1 = pd.DataFrame(info)
result = data1.values

excel = pd.read_excel("D:\\jupyter notebook 保存文件\\预处理21UEE92Q.xlsx")
data2 = pd.DataFrame(excel)
data_a = data2.values  # 变为数组

In [22]:
i=0
m = result[i][0]  # 运动学片段开始点
n = result[i][1]  # 运动学片段怠速状态结束点
k = result[i][2]+1  # 运动学片段结束点
v_average = sum(data_a[m:k,9])/(k-m)#平均速度
v_average_travel = sum(data_a[n:k,9])/(k-n)#平均行驶速度
v_max = max(data_a[m:k,9])#最大速度
plus = []#加速
slow = []#减速
uniformity = []#匀速
for j in range(n+1,k+1):
    acc = data_a[j][10]#索引10为加速度
    if acc > 0:
        plus.append(acc)
    if acc < 0:
        slow.append(acc)
    if acc == 0:
        uniformity.append(acc)
        
    # 平均加速度
plus_average = sum(plus)/len(plus)
    # 平均减速度
slow_average = sum(slow)/len(slow)
    # 速度标准差
v_std = np.std(data_a[m:k,9])
    # 加速度标准差
plus_std = np.std(plus)
    # 减速度标准差
slow_std = np.std(slow)
    # 运动学片段时长
time = k - m
    # 怠速时间
time_0 = n - m
    # 加速时间
time_1 = len(plus)
    # 减速时间
time_2 = len(slow)
    # 匀速时间
time_3 = len(uniformity)
    # 怠速时间比
ratio_0 = time_0/time
ratio_1 = time_1 / time
    # 减速时间比
ratio_2 = time_2 / time
    # 匀速时间比
ratio_3 = time_3 / time
                       
all = [v_average,v_average_travel,v_max,plus_average,slow_average,v_std,plus_std,slow_std,time,time_0,time_1,time_2,time_3,ratio_0,ratio_1,ratio_2,ratio_3]
all

[0.6216931216931213,
 1.0879629629629621,
 3.33333333333333,
 1.0416666666666676,
 -0.5456349206349208,
 0.9219016858043813,
 0.17010345435994303,
 0.43356693221055886,
 21,
 9,
 3,
 7,
 2,
 0.42857142857142855,
 0.14285714285714285,
 0.3333333333333333,
 0.09523809523809523]

In [12]:
plus = []#加速
slow = []#减速
uniformity = []#匀速
for j in range(n+1,k+1):
    acc = data_a[j][10]#索引10为加速度
    if acc > 0:
        plus.append(acc)
    if acc < 0:
        slow.append(acc)
    if acc == 0:
        uniformity.append(acc)

In [21]:
    # 平均加速度
plus_average = sum(plus)/len(plus)
    # 平均减速度
slow_average = sum(slow)/len(slow)
    # 速度标准差
v_std = np.std(data_a[m:k,9])
    # 加速度标准差
plus_std = np.std(plus)
    # 减速度标准差
slow_std = np.std(slow)
    # 运动学片段时长
time = k - m
    # 怠速时间
time_0 = n - m
    # 加速时间
time_1 = len(plus)
    # 减速时间
time_2 = len(slow)
    # 匀速时间
time_3 = len(uniformity)
    # 怠速时间比
ratio_0 = time_0/time
ratio_1 = time_1 / time
    # 减速时间比
ratio_2 = time_2 / time
    # 匀速时间比
ratio_3 = time_3 / time
                       
all = [v_average,v_average_travel,v_max,plus_average,slow_average,v_std,plus_std,slow_std,time,time_0,time_1,time_2,time_3,ratio_0,ratio_1,ratio_2,ratio_3]
all

[0.6216931216931213,
 1.0879629629629621,
 3.33333333333333,
 1.0416666666666676,
 -0.49479166666666685,
 0.9219016858043813,
 0.17010345435994303,
 0.4272914747999643,
 21,
 9,
 3,
 8,
 10,
 0.42857142857142855,
 0.14285714285714285,
 0.38095238095238093,
 0.47619047619047616]